name: Deploy Ingest Azure Function

on:
  workflow_run:
    workflows: ['Build Ingest Azure Function']
    types:
      - completed

jobs:
  call_reusable_workflow:
    uses: qurixtechnology/base-workflows/.github/workflows/deploy_azure_function.yml@main
    with:
      azure_function_app_name: func-dev-ingest-sunrise-core
      azure_function_app_build_path: ./sunrise/ingest/functions
      environment: dev
      python_version: 3.8
      current_branch: current_branch: ${{ github.head_ref }}
    secrets: inherit
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
