name: 'Infrastructure Build'
on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

jobs:
  tf_build_plan:
    uses: qurixtechnology/base-workflows/.github/workflows/build_terraform_plan.yml@fix/change-name
                                                           


