name: 'Infrastructure Build'
on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Init and plan'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: github.com/qurixtechnology/base-workflows/.github/workflows/build_terraform_plan@feature-terraform
        with:
          secrets: inherit



