name: 'Infrastructure Build'
on:
  push:
    branches:
      - main
      - 'feature/**'

  pull_request:
    branches:
      - main

jobs:
  terraform:
    uses: qurixtechnology/base-workflows/.github/workflows/build_terraform_plan.yml@feature-terraform      



