name: 'Sunrise Infrastructure Build'
on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'sunrise/**'
      - '.github/**'
  pull_request:
    branches:
      - main

jobs:
  call_reusable_workflow:    
    uses: qurixtechnology/base-workflows/.github/workflows/build_terraform_plan.yml@fix/change-name
    with:
      build_path: sunrise
      environment: dev
      use_case: sunrise-core
      aks_dns_prefix: sunrise
    secrets: inherit

